CREATE TABLE IF NOT EXISTS prefeitos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cidade_id INT UNSIGNED UNIQUE,
    FOREIGN KEY (cidade_id) REFERENCES cidades (id)
);