/* Modelagem básica - 

ENTIDADE =TABELA
ATRIBUTO =CAMPOS*/

CLIENTE

NOME - CARACTER (30)
CPF - NUMERICO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)
ENDERECO - CARACTER (100)
SEXO - CARACTER (1)

/* PROCESSOS DE MODELAGEM */

/* FASE 1 E 2 - ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LOGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 3 - DBA/AD */
MODELAGEM FISICA - 

/* CRIANDO BANCO DE DADOS */

CREATE DATABASE NOME;

/* CONECTANDO BANCO DE DADOS */

USE NOME

/* VERIFICAR QUAL BD ESTA CONECTADO */

STATUS

/* CRIANDO TABELA */
CREATE TABLE CLIENTE(
NOME VARCHAR(30),
SEXO CHAR(1),
EMAIL VARCHAR(30),
CPF INT(11),
TELEFONE VARCHAR(30),
ENDERECO VARCHAR(100)

);

CREATE TABLE LIVROS (
NOME_LIVRO VARCHAR(100),
NOME_AUTOR VARCHAR(100),
SEXO_AUTOR CHAR(1),
NUMERO_PAGINA INT(3),
NOME_EDITORA VARCHAR(100),
VALOR_LIVRO VARCHAR(6),
ESTADO_EDITORA CHAR(2),
ANO_PUBLICACAO CHAR (4)

);


/* VERIFICANDO TABELA */

SHOW TABLES;

/* DESCOBRINDO ESTRUTURA DA TABELA */

DESC NOMEDATABELA;

/* SINTAXE BASICA DE INSERCAO */

/*OMITINDO COLUNAS */

INSERT INTO CLIENTE VALUES('JOAO', 'M', '123@MAIL.COM', 101010-10, '123456789', 'RUA BLABLABLA N1');

/*DESCREVENDO COLUNAS - MAIS SEGURO */

INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF,TELEFONE,ENDERECO) VALUES(
'JOAO', 'M', NULL, 101010-10, '123456789', 'RUA BLABLABLA N1'); 

INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF,TELEFONE,ENDERECO) VALUES(
'FABIANO', 'M', 'FABIANO.TI@VIAMAR.COM.BR', 101012-10, '123456788', 'RUA 123BLABLABLA N1'); 

INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINA,NOME_EDITORA,VALOR_LIVRO,ESTADO_EDITORA,ANO_PUBLICACAO)
VALUES('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson','130,98','RS','2018'),
('O poder da mente','Clara Mafra','F',120,'Continental','56,58','SP','2017');


/*COMANDO SELECT - SELEÇÃO, PROJEÇÃO E JUNÇÃO*/

/*PROJEÇÃO*/

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT * FROM CLIENTE;

/*SELECAO - FILTRA POR LINHA*/

/*WHERE = IGUAL*/
SELECT NOME,SEXO FROM CLIENTE
WHERE SEXO="M";

/*LIKE = CONTEM */
SELECT NOME,SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'N1';

/*CARACTER CORINGA = % QUALQUER COISA*/

SELECT NOME,SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%N1';


SELECT NOME,SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%BLABLABLA%';


SELECT NOME_AUTOR, SEXO_AUTOR FROM LIVROS WHERE ESTADO_EDITORA IN ('SP','RJ');

/*BUSCAR CAMPO NULO*/

SELECT NOME, EMAIL FROM FUNCIONARIOS
WHERE EMAIL IS NULL;

/*BUSCAR CAMPO QUE NAO SEJA NULO*/

SELECT NOME, EMAIL FROM FUNCIONARIOS
WHERE EMAIL IS NOT NULL;

/*UPDATE - INSERIR/ALTERAR CAMPO NA TABELA*/

UPDATE CLIENTE
SET EMAIL ='TESTE@TESTE.COM'
WHERE NOME ='JOAO';

/*DELETE - EXCLUI LINHA NA TABELA */

DELETE CLIENTE 
WHERE NOME='JOAO';
 /*------------------------------------------------------------------------ */

/*1ª FORMA NORMAL  */

/* 1 REGRA -TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA */

/* 2 REGRA -TODO CAMPO MULTIVALORADO(OU QUANDO FOR DIVISIVEL) 
SE TORNARA OUTRA TABELA - EXEMPLO: ENDEREÇO */

/* 3 REGRA - TODA TABELA NECESSITA DE PELO MENOS 1 CAMPO IDENTIFICADOR - PK*/

 /*------------------------------------------------------------------------ */
 
 


